name: Gradle Package

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release Version
        required: true
        type: string
      snapshot-tag:
        description: New Version
        required: true
        type: string
      patch:
        description: Is patch?
        required: true
        default: false
        type: boolean
      release:
        description: Is release?
        required: true
        default: false
        type: boolean

jobs:

  tag-release:
    permissions:
      contents: write

    runs-on: [ self-hosted ]

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
      - name: Push Tag
        id: commit-tag
        if: ${{ inputs.release || inputs.patch }}
        run: |
          echo ${{ inputs.tag }} > version.txt
          git commit -am "${{ inputs.tag }} released."
          git tag ${{ inputs.tag }}
          git push origin refs/tags/${{ inputs.tag }}

  build:

    permissions:
      contents: write
      packages: write

    needs: tag-release

    runs-on: [self-hosted]

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}

      - name: update-version
        if: ${{ inputs.release || inputs.patch }}
        run: |
          echo ${{ inputs.tag }} > version.txt

      - name: Setup BUILD_JAVA_HOME & BUILD_JAVA_VERSION
        run: |
          java -Xinternalversion
          echo "BUILD_JAVA_HOME=${JAVA_HOME}" >> $GITHUB_ENV
          echo "BUILD_JAVA_VERSION=8" >> $GITHUB_ENV

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Publish with Gradle
        run: ./gradlew publish --no-daemon

  update-tags:

    permissions:
      contents: write

    needs: build

    runs-on: [ self-hosted ]

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Update master
        if: ${{ inputs.release }}
        run: |
          echo ${{ inputs.snapshot-tag }} > version.txt
          git commit -am "post ${{ inputs.tag }} release bump"
          git push origin main