name: Gradle Package

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release Tag
        required: true
        type: string
      snapshot-tag:
        description: Release Tag
        required: true
        type: string

permissions: write-all

jobs:
  build:

    runs-on: [self-hosted]

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}

      - name: update-version
        run: |
          echo ${{ inputs.tag }} > version.txt

      - name: Setup BUILD_JAVA_HOME & BUILD_JAVA_VERSION
        run: |
          java -Xinternalversion
          echo "BUILD_JAVA_HOME=${JAVA_HOME}" >> $GITHUB_ENV
          echo "BUILD_JAVA_VERSION=8" >> $GITHUB_ENV

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Publish with Gradle
        run: ./gradlew publish --no-daemon

      - name: Commit New Tag
        run: |
          git commit -am "${{ inputs.tag }} released."
          git tag ${{ inputs.tag }}
          git push origin ${{ inputs.tag }}
          
          echo ${{ inputs.snapshot-tag }} > version.txt
          git commit -am "post release bump"
          git push origin HEAD:main
          
