name: Gradle Package

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: [self-hosted]
    permissions:
      contents: write
      packages: write

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}

      - name: update-version
        run: |
          echo 'Hi' > version.txt

      - name: Setup BUILD_JAVA_HOME & BUILD_JAVA_VERSION
        run: |
          java -Xinternalversion
          echo "BUILD_JAVA_HOME=${JAVA_HOME}" >> $GITHUB_ENV
          echo "BUILD_JAVA_VERSION=8" >> $GITHUB_ENV

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Publish with Gradle
        run: ./gradlew publish --no-daemon

      - name: Commit New Tag
        run: |
          git commit -am "v1 released." && git tag v1
          echo 'Bye' > version.txt
          git commit -am "post release bump"
          git push --atomic origin master v1
          
