name: Gradle Package

on:
  workflow_dispatch:

permissions: write-all

jobs:
  build:

    runs-on: [self-hosted]

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}

      - name: update-version
        run: |
          echo 'Hi' > version.txt

      - name: Setup BUILD_JAVA_HOME & BUILD_JAVA_VERSION
        run: |
          java -Xinternalversion
          echo "BUILD_JAVA_HOME=${JAVA_HOME}" >> $GITHUB_ENV
          echo "BUILD_JAVA_VERSION=8" >> $GITHUB_ENV

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Publish with Gradle
        run: ./gradlew publish --no-daemon

      - name: Commit New Tag
        run: |
          git commit -am "1.1.2 released."
          git tag 1.1.2
          git push origin 1.1.2
          
          echo 'Bye' > version.txt
          git commit -am "post release bump"
          git push origin main
          
